<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <PackageDescription>GDeflate compression codec for RedFox Compression.</PackageDescription>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\RedFox.Compression\RedFox.Compression.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Update="runtimes\win-x64\native\libgdeflate.dll" Link="libgdeflate.dll" CopyToOutputDirectory="PreserveNewest" Pack="true" PackagePath="runtimes\win-x64\native\libgdeflate.dll" />
  </ItemGroup>

  <ItemGroup>
    <None Include="..\..\..\licenses\GDeflate-LICENSE" Pack="true" PackagePath="licenses" Visible="false" />
    <None Include="..\..\..\licenses\LibDeflate-LICENSE" Pack="true" PackagePath="licenses" Visible="false" />
  </ItemGroup>

</Project>
