<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <IsPackable>false</IsPackable>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\RedFox.GameExtraction.CommandLine\RedFox.GameExtraction.CommandLine.csproj" />
    <ProjectReference Include="..\RedFox.GameExtraction.Template\RedFox.GameExtraction.Template.csproj" />
  </ItemGroup>

</Project>
