<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Silk.NET.Vulkan" Version="2.23.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\RedFox.Imaging\RedFox.Imaging.csproj" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Shaders\*.spv" />
    <None Include="Shaders\*.hlsl" />
  </ItemGroup>

</Project>
