<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <PackageDescription>IMA and Microsoft ADPCM audio codecs for RedFox Audio.</PackageDescription>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\RedFox.Audio\RedFox.Audio.csproj" />
  </ItemGroup>

</Project>
