<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <PackageDescription>Asset management, handlers, and export pipeline for building game extraction tools.</PackageDescription>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\RedFox.Audio.ADPCM\RedFox.Audio.ADPCM.csproj" />
    <ProjectReference Include="..\RedFox.Audio.Flac\RedFox.Audio.Flac.csproj" />
    <ProjectReference Include="..\RedFox.Audio.Opus\RedFox.Audio.Opus.csproj" />
    <ProjectReference Include="..\RedFox.Audio\RedFox.Audio.csproj" />
    <ProjectReference Include="..\RedFox.Compression.Deflate\RedFox.Compression.Deflate.csproj" />
    <ProjectReference Include="..\RedFox.Compression.LZ4\RedFox.Compression.LZ4.csproj" />
    <ProjectReference Include="..\RedFox.Compression.ZStandard\RedFox.Compression.ZStandard.csproj" />
    <ProjectReference Include="..\RedFox.Compression\RedFox.Compression.csproj" />
    <ProjectReference Include="..\RedFox.Cryptography.MurMur3\RedFox.Cryptography.MurMur3.csproj" />
    <ProjectReference Include="..\RedFox.GameExtraction.Hashing\RedFox.GameExtraction.Hashing.csproj" />
    <ProjectReference Include="..\\RedFox.Imaging\\RedFox.Imaging.csproj" />
    <ProjectReference Include="..\RedFox.Graphics3D.OpenGL\RedFox.Graphics3D.OpenGL.csproj" />
    <ProjectReference Include="..\RedFox.Graphics3D\RedFox.Graphics3D.csproj" />
    <ProjectReference Include="..\RedFox.IO\RedFox.IO.csproj" />
    <ProjectReference Include="..\RedFox.IO.ProcessMemory\RedFox.IO.ProcessMemory.csproj" />
    <ProjectReference Include="..\RedFox\RedFox.csproj" />
    <ProjectReference Include="..\RedFox.Graphics3D.Formats\RedFox.Graphics3D.Formats.csproj" />
    <ProjectReference Include="..\RedFox.Imaging.Formats\RedFox.Imaging.Formats.csproj" />
  </ItemGroup>
</Project>