<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <PackageDescription>Process discovery and memory reading and writing for RedFox.</PackageDescription>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\RedFox.IO\RedFox.IO.csproj" />
    <ProjectReference Include="..\RedFox.Patterns\RedFox.Patterns.csproj" />
  </ItemGroup>

</Project>
