<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <PackageDescription>Opus audio encoder and decoder for RedFox Audio.</PackageDescription>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\RedFox.Audio\RedFox.Audio.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Include="..\..\..\licenses\Opus-LICENSE" Pack="true" PackagePath="licenses" Visible="false" />
    <None Update="runtimes\win-x64\native\opus.dll" Link="opus.dll" CopyToOutputDirectory="PreserveNewest" Pack="true" PackagePath="runtimes\win-x64\native\opus.dll" />
  </ItemGroup>

</Project>
